/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_uniduesseldorf_dxram_utils_JNIconsole */

#ifndef _Included_de_uniduesseldorf_dxram_utils_JNIconsole
#define _Included_de_uniduesseldorf_dxram_utils_JNIconsole
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_uniduesseldorf_dxram_utils_JNIconsole
 * Method:    readline
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_de_uniduesseldorf_dxram_utils_JNIconsole_readline
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
