#!/bin/bash

if [ "$#" -lt 1 ]; then
	echo "Usage: $0 <dxram peer hostname/ipv4> [port, default: 22220]"
	exit 1
fi

DIR="$(cd "$(dirname "$0")"; pwd)"
PORT=$2

if [ "$PORT" = "" ]; then
	PORT="22220"
fi

java -Dlog4j.configurationFile=$DIR/config/log4j.xml -cp $DIR/dxterm-client.jar:$DIR/dxram.jar:$DIR/lib/* de.hhu.bsinfo.dxterm.TerminalClient "$1" "$PORT" 
