#!/bin/bash

if [ "$#" -ne 2 ]; then
	echo "Usage: $0 <dxram peer hostname/ipv4> <port>"
	exit 1
fi

java -Dlog4j.configurationFile=config/log4j.xml -cp bin/:lib/* de.hhu.bsinfo.dxterm.TerminalClient $1 $2
