/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_hhu_bsinfo_utils_JNIFileDirect */

#ifndef _Included_de_hhu_bsinfo_utils_JNIFileDirect
#define _Included_de_hhu_bsinfo_utils_JNIFileDirect
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_hhu_bsinfo_utils_JNIFileDirect
 * Method:    open
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_de_hhu_bsinfo_utils_JNIFileDirect_open
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     de_hhu_bsinfo_utils_JNIFileDirect
 * Method:    createBuffer
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_utils_JNIFileDirect_createBuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_hhu_bsinfo_utils_JNIFileDirect
 * Method:    freeBuffer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_hhu_bsinfo_utils_JNIFileDirect_freeBuffer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_hhu_bsinfo_utils_JNIFileDirect
 * Method:    close
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_hhu_bsinfo_utils_JNIFileDirect_close
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_hhu_bsinfo_utils_JNIFileDirect
 * Method:    write
 * Signature: (I[BIIJI)I
 */
JNIEXPORT jint JNICALL Java_de_hhu_bsinfo_utils_JNIFileDirect_write
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint, jlong, jint);

/*
 * Class:     de_hhu_bsinfo_utils_JNIFileDirect
 * Method:    dwrite
 * Signature: (I[BIIJI)I
 */
JNIEXPORT jint JNICALL Java_de_hhu_bsinfo_utils_JNIFileDirect_dwrite
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint, jlong, jint);

/*
 * Class:     de_hhu_bsinfo_utils_JNIFileDirect
 * Method:    read
 * Signature: (I[BIIJI)I
 */
JNIEXPORT jint JNICALL Java_de_hhu_bsinfo_utils_JNIFileDirect_read
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint, jlong, jint);

/*
 * Class:     de_hhu_bsinfo_utils_JNIFileDirect
 * Method:    seek
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_utils_JNIFileDirect_seek
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     de_hhu_bsinfo_utils_JNIFileDirect
 * Method:    length
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_utils_JNIFileDirect_length
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_hhu_bsinfo_utils_JNIFileDirect
 * Method:    setFileLength
 * Signature: (IJ)I
 */
JNIEXPORT jint JNICALL Java_de_hhu_bsinfo_utils_JNIFileDirect_setFileLength
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     de_hhu_bsinfo_utils_JNIFileDirect
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_hhu_bsinfo_utils_JNIFileDirect_test
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
